language: android

android:
  components:
    - tools
    - tools
    - android-23
    - android-24
    - android-25
    - build-tools-25.0.2
    - build-tools-24.0.1
    - build-tools-23.0.2
    - build-tools-23.0.3
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

script: ./gradlew check
